apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weightr-backend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-wb@kubernetescrd
spec:
  rules:
  {{- if .Values.ingress.host }}
  # ── PRODUCTION: host-based routing ────────────────
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: weightr-backend
            port:
              number: 80
  {{- else }}
  # ── DEVELOPMENT: no host, catch-all rule ─────────
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: weightr-backend
            port:
              number: 80
  {{- end }}