apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weightr-backend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-wb@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /weightr-backend
        pathType: Prefix
        backend:
          service:
            name: weightr-backend
            port:
              number: 80