version: 1
disable_existing_loggers: False

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s %(pathname)s %(lineno)d"

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: /mnt/nas_server/var/data/weightr-backend/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    level: DEBUG

loggers:
  uvicorn:
    level: WARNING
    handlers: [file]
    propagate: False

  app:
    level: DEBUG
    handlers: [file]
    propagate: False

root:
  level: WARNING
  handlers: [file]
