apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-weightr-backend-conf-pv
  labels:
    app: weightr-backend
    datatype: conf
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath
  hostPath:
    path: /mnt/var/conf/weightr-backend
    type: DirectoryOrCreate
