apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-weightr-backend-conf
spec:
  storageClassName: manual-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: weightr-backend
      datatype: conf