apiVersion: v1
kind: Service
metadata:
  name: weightr-backend
  labels:
    app: weightr-backend
spec:
  selector:
    app: weightr-backend
  ports:
  - port: 80
    targetPort: 8088
    name: web
  type: ClusterIP
