server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: weightr-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: weightr-backend
          __path__: /logs/weightr-backend/*.log
